range_x: [0, 333.33]
range_y: [-100.0, 66.66]
range_t: [0.0, 1500.0]
lim_x: [0, 300.0]
lim_y: [-100.0, 66.66]
annotation_cols: 3
annotation_rows: 2
field_scale_fact: 1.0e5
annotations:
 - pos: [2, -30]
   range_t: [320.0, 375.0]
 - pos: [30, -20]
   range_t: [0.0, 30.0]
 - pos: [30, -50]
   range_t: [0.0, 30.0]
 - pos: [30, -90]
   range_t: [0.0, 30.0]
 - pos: [200, -20]
   range_t: [0.0, 30.0]
 - pos: [200, -50]
   range_t: [0.0, 30.0]