name: build

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: "Test compilation"
    runs-on: ubuntu-latest

  steps:
  - name: Install dependencies
    run: |
      sudo apt-get -y update
      sudo apt-get -y pkg-config cmake
      sudo apt-get -y libhdf5-mpi-dev libharminv-dev libfftw3-dev libgsl-dev libgslcblas0
      sudo apt-get -y python3-setuptools cython3 python3-matplotlib python3-mpi4py
      sudo apt-get -y python3-meep-mpi-default libmeep-mpi-default-dev