name: tests

on: [push, pull_request, workflow_dispatch]

jobs:
  build_and_test:
    name: "Run build and tests"
    runs-on: ubuntu-latest
    steps:
    
    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get install -y pkg-config cmake
	sudo apt-get install -y libtbb-dev
        sudo apt-get install -y libhdf5-mpi-dev libharminv-dev libfftw3-dev libgsl-dev libgslcblas0
        sudo apt-get install -y python3-setuptools cython3 python3-matplotlib python3-mpi4py
        sudo apt-get install -y python3-meep-mpi-default libmeep-mpi-default-dev

    - name: Checkout Eisvogel repository
      uses: actions/checkout@v4

    - name: Compile Eisvogel
      run: |
        mkdir -p build &&
        pushd build &&
        cmake -DBUILD_PYTHON=ON -DBUILD_WFC=ON -DBUILD_TESTS=ON ../ &&
        VERBOSE=1 make &&
        popd

    - name: Run C++ tests
      run: |
        bash tests/run_tests.sh build/

    - name: Run python tests
      run: |
        source build/setup.sh &&
        python3 -m unittest discover -s cpython/tests/

