name: build

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: "Test compilation"
    runs-on: ubuntu-latest
    steps:
    
    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get install -y pkg-config cmake
        sudo apt-get install -y libhdf5-mpi-dev libharminv-dev libfftw3-dev libgsl-dev libgslcblas0
        sudo apt-get install -y python3-setuptools cython3 python3-matplotlib python3-mpi4py
        sudo apt-get install -y python3-meep-mpi-default libmeep-mpi-default-dev

    - name: Checkout Eisvogel repository
      uses: actions/checkout@v3

    - name: Compile Eisvogel
      run: |
        mkdir -p build &&
        pushd build &&
        cmake ../ &&
        make &&
        popd

    - name: Run python tests
      run: |
        source build/setup.sh &&
        pushd cpython/tests &&
        for CUR_FILE in `ls *.py`
        do
          python3 ${CUR_FILE}
        done &&
        popd

